---
name: Query-Punq
version: 0.03
author:
  - David Wheeler <david@kineticode.com>
abstract: Track changes between documents
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Algorithm::Diff: 1.19
  HTML::Entities: 0
  Term::ANSIColor: 0
build_requires:
  File::Spec: 0
  Test::Simple: 0.17
provides:
  Query::Punq:
    file: lib/Query/Punq.pm
    version: 0.03
  Query::Punq::ANSIColor:
    file: lib/Query/Punq/ANSIColor.pm
    version: 0.03
  Query::Punq::Base:
    file: lib/Query/Punq.pm
  Query::Punq::HTML:
    file: lib/Query/Punq/HTML.pm
    version: 0.03
generated_by: Module::Build version 0.2702
